const icons={wk:'♔',wq:'♕',wr:'♖',wb:'♗',wn:'♘',wp:'♙',bk:'♚',bq:'♛',br:'♜',bb:'♝',bn:'♞',bp:'♟'};
let board=[],turn='w',selected=null,moves=[],gameOver=false,cpuThinking=false,cpuTimer=null;
let castleRights={w:{king:true,queen:true},b:{king:true,queen:true}};
const boardElement=document.querySelector('#chess-board'),modeElement=document.querySelector('#game-mode');
document.querySelector('#reset').onclick=resetChess;modeElement.onchange=resetChess;

function resetChess(){clearTimeout(cpuTimer);board=[...'rnbqkbnr'].map(x=>'b'+x).concat(Array(8).fill('bp'),Array(32).fill(''),Array(8).fill('wp'),[...'rnbqkbnr'].map(x=>'w'+x));turn='w';selected=null;moves=[];gameOver=false;cpuThinking=false;castleRights={w:{king:true,queen:true},b:{king:true,queen:true}};modeElement.disabled=false;render();status(modeElement.value==='cpu'?'You are White. Select a piece to move.':'Select a piece to move')}
function status(message){document.querySelector('#chess-turn').textContent=gameOver?'GAME OVER':cpuThinking?'CPU':turn==='w'?'WHITE':'BLACK';document.querySelector('#chess-message').textContent=message}
function render(){boardElement.innerHTML='';boardElement.classList.toggle('game-over',gameOver);board.forEach((piece,index)=>{const square=document.createElement('button');square.className='square '+((Math.floor(index/8)+index%8)%2?'dark':'light')+(index===selected?' selected':'')+(moves.includes(index)?' move':'');square.textContent=piece?icons[piece]:'';square.disabled=gameOver||cpuThinking;if(piece)square.classList.add(piece[0]==='w'?'white-piece':'black-piece');square.onclick=()=>clickSquare(index);boardElement.appendChild(square)})}
function clickSquare(index){if(gameOver||cpuThinking||(modeElement.value==='cpu'&&turn==='b'))return;const piece=board[index];if(selected!==null&&moves.includes(index)){makeMove(selected,index);return}if(piece&&piece[0]===turn){selected=index;moves=pieceMoves(index,piece);render();status(moves.length?'Choose a highlighted square':'No moves available')}else{selected=null;moves=[];render()}}
function makeMove(from,to){const moving=board[from],captured=board[to],side=moving[0],earnsRewards=modeElement.value==='player'||side==='w';board[to]=moving;board[from]='';if(moving[1]==='k'&&Math.abs(to-from)===2){const rookFrom=to>from?from+3:from-4,rookTo=to>from?to-1:to+1;board[rookTo]=board[rookFrom];board[rookFrom]=''}if(moving[1]==='k'){castleRights[side].king=false;castleRights[side].queen=false}if(moving[1]==='r'){const home=side==='w'?56:0;if(from===home)castleRights[side].queen=false;if(from===home+7)castleRights[side].king=false}if(moving[1]==='p'&&(to<8||to>55))board[to]=moving[0]+'q';selected=null;moves=[];if(captured&&earnsRewards)PixelRewards.earn(captured[1]==='k'?27:2,captured[1]==='k'?'CHESS CAPTURE + WIN':'CHESS CAPTURE');if(captured&&captured[1]==='k'){gameOver=true;cpuThinking=false;modeElement.disabled=true;render();status((side==='w'?'White':'Black')+' has won the game! Reset to play again.');return}turn=turn==='w'?'b':'w';render();status('Select a piece to move');if(modeElement.value==='cpu'&&turn==='b')startCpuTurn()}
function startCpuTurn(){cpuThinking=true;render();status('CPU is choosing a move…');cpuTimer=setTimeout(()=>{if(gameOver||modeElement.value!=='cpu'||turn!=='b')return;const choices=[];board.forEach((piece,from)=>{if(piece&&piece[0]==='b')pieceMoves(from,piece).forEach(to=>choices.push({from,to,capturesKing:board[to]==='wk'}))});cpuThinking=false;if(!choices.length){gameOver=true;modeElement.disabled=true;render();status('White has won the game! The CPU has no moves. Reset to play again.');return}const winning=choices.find(choice=>choice.capturesKing),choice=winning||choices[Math.floor(Math.random()*choices.length)];makeMove(choice.from,choice.to)},550)}
function pieceMoves(index,piece){let row=Math.floor(index/8),col=index%8,out=[],side=piece[0],type=piece[1];const add=(r,c)=>{if(r<0||r>7||c<0||c>7)return false;let target=r*8+c;if(!board[target]){out.push(target);return true}if(board[target][0]!==side)out.push(target);return false};const ray=(dr,dc)=>{let r=row+dr,c=col+dc;while(add(r,c)){r+=dr;c+=dc}};if(type==='p'){let d=side==='w'?-1:1,start=side==='w'?6:1,target=(row+d)*8+col;if(row+d>=0&&!board[target]){out.push(target);let double=(row+2*d)*8+col;if(row===start&&!board[double])out.push(double)}for(let dc of[-1,1]){let r=row+d,c=col+dc;if(r>=0&&r<8&&c>=0&&c<8&&board[r*8+c]&&board[r*8+c][0]!==side)out.push(r*8+c)}}if(type==='r'||type==='q')[[1,0],[-1,0],[0,1],[0,-1]].forEach(x=>ray(...x));if(type==='b'||type==='q')[[1,1],[1,-1],[-1,1],[-1,-1]].forEach(x=>ray(...x));if(type==='n')[[2,1],[2,-1],[-2,1],[-2,-1],[1,2],[1,-2],[-1,2],[-1,-2]].forEach(x=>add(row+x[0],col+x[1]));if(type==='k'){for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if(dr||dc)add(row+dr,col+dc);const home=side==='w'?60:4;if(index===home&&castleRights[side].king&&!board[home+1]&&!board[home+2]&&board[home+3]===side+'r')out.push(home+2);if(index===home&&castleRights[side].queen&&!board[home-1]&&!board[home-2]&&!board[home-3]&&board[home-4]===side+'r')out.push(home-2)}return out}
resetChess();
