const home=document.querySelector('#home'),game=document.querySelector('#game');
const panels={bike:document.querySelector('#bike-game'),chess:document.querySelector('#chess-game'),ttt:document.querySelector('#ttt-game')};
const meta={bike:['GAME 01','VEX X3M 3'],chess:['GAME 02','CHESS'],ttt:['GAME 03','TIC TAC TOE']};let current='bike';
document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>openGame(b.dataset.game));
document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>{home.classList.add('active');game.classList.remove('active');stopBike()});
document.querySelector('#reset').onclick=()=>({bike:resetBike,chess:resetChess,ttt:resetTTT}[current]());
function openGame(id){current=id;home.classList.remove('active');game.classList.add('active');Object.values(panels).forEach(p=>p.classList.remove('active'));panels[id].classList.add('active');document.querySelector('#game-kicker').textContent=meta[id][0];document.querySelector('#game-title').textContent=meta[id][1];if(id==='bike')startBike();}

// Tic tac toe
let ttt=[],turn='X',scores={X:0,O:0},ended=false;const tboard=document.querySelector('#ttt-board');
function resetTTT(){ttt=Array(9).fill('');turn='X';ended=false;tboard.innerHTML='';for(let i=0;i<9;i++){let b=document.createElement('button');b.className='ttt-cell';b.onclick=()=>tttMove(i,b);tboard.appendChild(b)}setTTT('X','Your move')}
function setTTT(t,msg){document.querySelector('#ttt-turn').textContent=t;document.querySelector('#ttt-message').textContent=msg;document.querySelector('#x-score').textContent=scores.X;document.querySelector('#o-score').textContent=scores.O}
function tttMove(i,b){if(ttt[i]||ended)return;ttt[i]=turn;b.textContent=turn;b.classList.add(turn.toLowerCase());let wins=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];let win=wins.find(w=>w.every(n=>ttt[n]===turn));if(win){ended=true;scores[turn]++;win.forEach(n=>tboard.children[n].style.borderColor='#d7ff38');setTTT(turn,turn+' takes the round!');return}if(ttt.every(Boolean)){ended=true;setTTT('—','Draw game');return}turn=turn==='X'?'O':'X';setTTT(turn,'Your move')}
resetTTT();

// Chess: local two-player with legal piece movement and captures.
const icons={wk:'♔',wq:'♕',wr:'♖',wb:'♗',wn:'♘',wp:'♙',bk:'♚',bq:'♛',br:'♜',bb:'♝',bn:'♞',bp:'♟'};let cb=[],cturn='w',selected=null,moves=[];const cboard=document.querySelector('#chess-board');
function resetChess(){cb=[...'rnbqkbnr'].map(x=>'b'+x).concat(Array(8).fill('bp'),Array(32).fill(''),Array(8).fill('wp'),[...'rnbqkbnr'].map(x=>'w'+x));cturn='w';selected=null;moves=[];renderChess();chessStatus('Select a piece to move')}
function chessStatus(msg){document.querySelector('#chess-turn').textContent=cturn==='w'?'WHITE':'BLACK';document.querySelector('#chess-message').textContent=msg}
function renderChess(){cboard.innerHTML='';cb.forEach((p,i)=>{let b=document.createElement('button');b.className='square '+((Math.floor(i/8)+i%8)%2?'dark':'light')+(i===selected?' selected':'')+(moves.includes(i)?' move':'');b.innerHTML=p?icons[p]:'';if(p)b.classList.add(p[0]==='w'?'white-piece':'black-piece');b.onclick=()=>chessClick(i);cboard.appendChild(b)})}
function chessClick(i){let p=cb[i];if(selected!==null&&moves.includes(i)){let moving=cb[selected];cb[i]=moving;cb[selected]='';if(moving[1]==='p'&&(i<8||i>55))cb[i]=moving[0]+'q';cturn=cturn==='w'?'b':'w';selected=null;moves=[];renderChess();chessStatus(p&&p[1]==='k'?(cturn==='w'?'Black':'White')+' wins!':'Select a piece to move');return}if(p&&p[0]===cturn){selected=i;moves=pieceMoves(i,p);renderChess();chessStatus(moves.length?'Choose a highlighted square':'No moves available')}else{selected=null;moves=[];renderChess()}}
function pieceMoves(i,p){let r=Math.floor(i/8),c=i%8,out=[],side=p[0],type=p[1];const add=(rr,cc)=>{if(rr<0||rr>7||cc<0||cc>7)return false;let q=rr*8+cc;if(!cb[q]){out.push(q);return true}if(cb[q][0]!==side)out.push(q);return false};const ray=(dr,dc)=>{let rr=r+dr,cc=c+dc;while(add(rr,cc)){rr+=dr;cc+=dc}};if(type==='p'){let d=side==='w'?-1:1,start=side==='w'?6:1,q=(r+d)*8+c;if(r+d>=0&&!cb[q]){out.push(q);let q2=(r+2*d)*8+c;if(r===start&&!cb[q2])out.push(q2)}for(let dc of[-1,1]){let rr=r+d,cc=c+dc;if(rr>=0&&rr<8&&cc>=0&&cc<8&&cb[rr*8+cc]&&cb[rr*8+cc][0]!==side)out.push(rr*8+cc)}}if(type==='r'||type==='q')[[1,0],[-1,0],[0,1],[0,-1]].forEach(x=>ray(...x));if(type==='b'||type==='q')[[1,1],[1,-1],[-1,1],[-1,-1]].forEach(x=>ray(...x));if(type==='n')[[2,1],[2,-1],[-2,1],[-2,-1],[1,2],[1,-2],[-1,2],[-1,-2]].forEach(x=>add(r+x[0],c+x[1]));if(type==='k')for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if(dr||dc)add(r+dr,c+dc);return out}
resetChess();

// Canvas bike runner
const canvas=document.querySelector('#bike-canvas'),ctx=canvas.getContext('2d'),keys={};let bike,terrain=[],bikeRAF=0,last=0;
addEventListener('keydown',e=>{keys[e.key]=true;if(e.key.toLowerCase()==='r'&&current==='bike')resetBike()});addEventListener('keyup',e=>keys[e.key]=false);
function resetBike(){bike={x:100,y:310,vx:0,vy:0,angle:0,spin:0,started:false,done:false,start:0};terrain=[];for(let x=0;x<=3100;x+=100){let y=400;if(x>350)y=390+Math.sin(x*.009)*48;if(x>900&&x<1200)y=430-(x-900)*.35;if(x>=1200&&x<1450)y=325+(x-1200)*.3;if(x>1800&&x<2050)y=410-(x-1800)*.45;terrain.push({x,y})}last=performance.now();}
function groundAt(x){let a=terrain[Math.max(0,Math.min(terrain.length-2,Math.floor(x/100)))],b=terrain[Math.min(terrain.length-1,Math.floor(x/100)+1)];return a.y+(b.y-a.y)*(x-a.x)/(b.x-a.x)}
function startBike(){resetBike();cancelAnimationFrame(bikeRAF);bikeRAF=requestAnimationFrame(bikeLoop)}function stopBike(){cancelAnimationFrame(bikeRAF)}
function bikeLoop(t){let dt=Math.min(.025,(t-last)/1000||.016);last=t;if(keys.ArrowUp&&!bike.done){bike.vx=Math.min(280,bike.vx+200*dt);if(!bike.started){bike.started=true;bike.start=t}}else bike.vx*=Math.pow(.992,dt*60);if(keys.ArrowDown)bike.vx*=.96;if(keys.ArrowLeft)bike.spin-=3.2*dt;if(keys.ArrowRight)bike.spin+=3.2*dt;bike.vy+=650*dt;bike.x+=bike.vx*dt;bike.y+=bike.vy*dt;bike.angle+=bike.spin;let g=groundAt(bike.x);if(bike.y>g-27){bike.y=g-27;bike.vy=Math.min(0,bike.vy)*-.2;bike.spin*=.82;let slope=(groundAt(bike.x+5)-groundAt(bike.x-5))/10,target=Math.atan(slope);bike.angle+=(target-bike.angle)*.12}if(bike.x>=2950&&!bike.done){bike.done=true;let time=(t-bike.start)/1000,best=localStorage.getItem('pp-bike-best');if(!best||time<best){best=time;localStorage.setItem('pp-bike-best',time)}document.querySelector('#bike-best').textContent=Number(best).toFixed(1)}drawBike(t);bikeRAF=requestAnimationFrame(bikeLoop)}
function drawBike(t){let cam=Math.max(0,bike.x-220);ctx.clearRect(0,0,960,500);let sky=ctx.createLinearGradient(0,0,0,500);sky.addColorStop(0,'#20243a');sky.addColorStop(1,'#ff5a36');ctx.fillStyle=sky;ctx.fillRect(0,0,960,500);ctx.fillStyle='#d7ff38';ctx.beginPath();ctx.arc(780-cam*.08,100,48,0,7);ctx.fill();ctx.fillStyle='#111520';ctx.beginPath();ctx.moveTo(-cam,500);terrain.forEach(p=>ctx.lineTo(p.x-cam,p.y));ctx.lineTo(3100-cam,500);ctx.fill();ctx.strokeStyle='#d7ff38';ctx.lineWidth=4;ctx.beginPath();terrain.forEach((p,i)=>i?ctx.lineTo(p.x-cam,p.y):ctx.moveTo(p.x-cam,p.y));ctx.stroke();ctx.save();ctx.translate(bike.x-cam,bike.y);ctx.rotate(bike.angle);ctx.strokeStyle='#f2efe6';ctx.lineWidth=5;for(let x of[-17,17]){ctx.beginPath();ctx.arc(x,12,12,0,7);ctx.stroke()}ctx.strokeStyle='#d7ff38';ctx.beginPath();ctx.moveTo(-17,12);ctx.lineTo(0,-9);ctx.lineTo(17,12);ctx.lineTo(-5,9);ctx.lineTo(-17,12);ctx.stroke();ctx.fillStyle='#ff5a36';ctx.beginPath();ctx.arc(0,-20,8,0,7);ctx.fill();ctx.restore();ctx.fillStyle='#fff';ctx.font='11px DM Mono';ctx.fillText('FINISH',2950-cam,260);ctx.fillStyle='#d7ff38';ctx.fillRect(2950-cam,270,5,140);let elapsed=bike.started?(bike.done?0:(t-bike.start)/1000):0;document.querySelector('#bike-time').textContent=elapsed.toFixed(1);let best=localStorage.getItem('pp-bike-best');document.querySelector('#bike-best').textContent=best?Number(best).toFixed(1):'--'}
resetBike();
